In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good'
        ]

In [3]:
voc_size = 10000

In [4]:
one_hot_rep = [one_hot(words, voc_size) for words in sent]
one_hot_rep

[[6563, 9354, 2130, 2241],
 [6563, 9354, 2130, 9250],
 [6563, 132, 2130, 8440],
 [9642, 3251, 1182, 2244, 1196],
 [9642, 3251, 1182, 2244, 2737],
 [642, 6563, 2032, 2130, 3765],
 [4122, 4518, 3469, 2244]]

In [6]:
#Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6563 9354 2130 2241]
 [   0    0    0    0 6563 9354 2130 9250]
 [   0    0    0    0 6563  132 2130 8440]
 [   0    0    0 9642 3251 1182 2244 1196]
 [   0    0    0 9642 3251 1182 2244 2737]
 [   0    0    0  642 6563 2032 2130 3765]
 [   0    0    0    0 4122 4518 3469 2244]]


In [9]:
#feature representation
dim=10

In [17]:
model = Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim,input_length=8))
model.compile('adam','mse')
model.build(input_shape=(None,8))

c:\Users\plava\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step


array([[[ 0.03138917, -0.04451991, -0.04280603, -0.04048823,
          0.00919415,  0.03086862,  0.01927208,  0.00363735,
          0.02839409,  0.04876169],
        [ 0.03138917, -0.04451991, -0.04280603, -0.04048823,
          0.00919415,  0.03086862,  0.01927208,  0.00363735,
          0.02839409,  0.04876169],
        [ 0.03138917, -0.04451991, -0.04280603, -0.04048823,
          0.00919415,  0.03086862,  0.01927208,  0.00363735,
          0.02839409,  0.04876169],
        [ 0.03138917, -0.04451991, -0.04280603, -0.04048823,
          0.00919415,  0.03086862,  0.01927208,  0.00363735,
          0.02839409,  0.04876169],
        [ 0.00707288, -0.00210645, -0.02725533,  0.04529685,
         -0.00881694,  0.01916045, -0.02161311,  0.01793167,
         -0.01420572,  0.0042216 ],
        [ 0.03425112,  0.03525492, -0.00587354, -0.04367124,
          0.0171015 ,  0.0388251 ,  0.0373988 , -0.04004289,
          0.0475479 , -0.04965053],
        [ 0.03372718, -0.04755152, -0.01529082, -0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0, 6563, 9354, 2130, 2241])

In [ ]:
model.predict(embedded_docs[0])